{% set name = "nc-time-axis" %}
{% set version = "3.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: adb8148294332e00e46a3b7b15ee1fb4d1231f8d23276b6290d64b1ecf2539d0

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.7
    - pip
    - numpy
    - cython
    - udunits2
    - setuptools-scm
  run:
    - {{ pin_compatible('udunits2', max_pin='x.x') }}
    - python >=3.7
    - cftime >=1.2
    - {{ pin_compatible('numpy') }}
    - antlr-python-runtime 4.7.2.*

test:
  requires:
    - pytest
    - pip
  imports:
    - cf_units
  commands:
    - pip check
    - pytest --pyargs cf_units

about:
  home: https://cf-units.readthedocs.io/en/latest/
  license: LGPL-3.0-or-later
  license_file: COPYING.LESSER
  summary: Units of measure as required by the Climate and Forecast (CF) metadata conventions.

extra:
  recipe-maintainers:
    - bjlittle
    - ocefpaf
    - pelson
    - trexfeathers
