{% set name = "cf-units" %}
{% set version = "3.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9aefa5d16235d0e7110f83873270d502cb9b6fe07fc8cb472999d813a155eae2

build:
  number: 1
  skip: True  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
 
  host:
    - python
    - pip
    - numpy
    - cython
    - udunits2
    - setuptools-scm
  run:
    - {{ pin_compatible('udunits2', max_pin='x.x') }}
    - python
    - cftime >=1.2
    - {{ pin_compatible('numpy') }}
    - antlr-python-runtime 4.7.2.*
    - jinja2

test:
  requires:
    - pytest
    - pip
  imports:
    - cf_units
  commands:
    - pip check
    # remove the tests exclusion when https://github.com/SciTools/cf-units/pull/207 is merged
    - pytest --pyargs cf_units -k "not (test_unit_power or test_unit_power or test_unit_power)"

about:
  home: https://cf-units.readthedocs.io/en/latest/
  license: LGPL-3.0-or-later
  license_file: COPYING.LESSER
  summary: Units of measure as required by the Climate and Forecast (CF) metadata conventions.

extra:
  recipe-maintainers:
    - bjlittle
    - ocefpaf
    - pelson
    - trexfeathers
