{% set version = "3.0.0" %}

package:
  name: cf-units
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cf-units/cf-units-{{ version }}.tar.gz
  sha256: adb8148294332e00e46a3b7b15ee1fb4d1231f8d23276b6290d64b1ecf2539d0

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython
    - udunits2
    # It isn't clear that this really is needed, but it is listed in setup.py.
    - pytest-runner
  run:
    - {{ pin_compatible('udunits2', max_pin='x.x') }}
    - python
    - cftime
    - {{ pin_compatible('numpy') }}
    - antlr-python-runtime 4.7.2.*
    - six  # not really needed but still listed and check by pip

test:
  requires:
    - pytest
    - pip
  imports:
    - cf_units
  commands:
    - pip check
    - pytest --pyargs cf_units

about:
  home: https://scitools.org.uk/cf-units/docs/latest/
  license: LGPL-3.0-or-later
  license_file: COPYING.LESSER
  summary: Units of measure as required by the Climate and Forecast (CF) metadata conventions.

extra:
  recipe-maintainers:
    - bjlittle
    - ocefpaf
    - pelson
    - trexfeathers
