appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: yg1xN+yTAUlolljIJNIRUDv82hVxEddWU5Nr+kI0fnBeV5iUTKcEsJFhkQRiDZlMCJcYNYXZ1kUmBFR05kGa6HaWj09hTLmnWCWaPe+3bK1RyX5wLsOSRwuBz//ibM0O26qJC2Ao6P4V3bF8/6gK3PCK7EbTl67jambJ+aAJxWYGUJcjKEcSuvrtFzj9fQtGOelETndbUrAPgmvszcsggM5zMFt4KhduzVX1wew1qoifqnin0Mi0LymYFxv/sT81CWK1bbRtuAHHiPNnXLgSKi86ZhTofVbn9IyfSNQ6l/n+x3xJWbbSq1oRijz6p/m4UAnuwZU8vBK6HlPBgmrfAB4V9zyzr4wQyWYiQs5wg70EWzX902wtWwHZc0KeTU6Ezo9mtya8w1M+amFEeHp8Hyl0D+NpiD4cB08pqsFyTX0YQd8rI5qqMlD5aPx9LrDJ4RlimMSUE+aij2kR2NSth1e2yHOoHKETdD7C9jyX/ivbHaqJYF7T6N/fF7x9siBAIoqHUIdtrX9nrSD3ZxsdJnrMfERbBG8UVsZI5uC9cGERIbPONzh9jMQFMc6Qhqezr/uJ4iWtm/X7nUuncBvEaoSZ8NHMq0cNdbnzD1zEmC37Bi7JHKcEXDPgevp/RfJKBFe6EpbfRgRHK8//ObV1mBd8xnXZV+qitzH6qngIsws=}
provider:
  osx: azure
  linux: azure
  win: azure
